### ISSUE TITLE
Child expand error!

### ISSUE THREAD

**Issue by phucvo0709** [hjyue1/react-do-tree-select#3] opened 2019-03-01 07:49 UTC
I see children displaying errors and how to fix them?

![untitled-1](https://user-images.githubusercontent.com/35060381/53623934-21d23880-3c31-11e9-93f9-0caee8e77a57.png)

**Comment by hjyue1** [comment] 2019-03-01 13:36
@phucvo0709 Hello, I'm very sorry. I just saw your problem. Could you please provide an online example to reproduce this scene

**Comment by phucvo0709** [comment] 2019-03-01 18:11
https://codesandbox.io/embed/ypl0krpzn1?fontsize=14

**Comment by hjyue1** [comment] 2019-03-04 02:28
@phucvo0709 Hi，This problem was fixed in version 1.3.6 because the value field type of treeData is not a string

**Comment by phucvo0709** [comment] 2019-03-04 02:33
thanks you very much! 
You can add function auto suggest find function without pressing enter?

**Comment by hjyue1** [comment] 2019-03-04 02:40
@phucvo0709  For performance reasons, it is recommended to use the enter key trigger
but your suggestion is very good, Consider adding this feature later

**Comment by phucvo0709** [comment] 2019-03-04 02:46
> @phucvo0709 For performance reasons, it is recommended to use the enter key trigger
> but your suggestion is very good, Consider adding this feature later

ok I will continue to use your plugin if I have more problems I will comment

**Comment by hjyue1** [comment] 2019-03-04 03:09
@phucvo0709 Okay, so I'm going to close this issue

**Closed as completed by hjyue1** 2019-03-04 03:09 UTC
