### ISSUE TITLE
Error with css!

### ISSUE THREAD

**Issue by phucvo0709** [hjyue1/react-do-tree-select#2] opened 2019-02-25 08:34 UTC
![untitled](https://user-images.githubusercontent.com/35060381/53324177-b7f51e80-3912-11e9-8921-97939b16b077.png)

**Comment by hjyue1** [comment] 2019-02-25 08:44
@phucvo0709  Could be a build tool issue, Do you have webpack loader ?

**Comment by phucvo0709** [comment] 2019-02-25 09:33
> @phucvo0709 Could be a build tool issue, Do you have webpack loader ?

my code config

```
const withCSS = require('@zeit/next-css');
const withSass = require('@zeit/next-sass');
const withLess = require('@zeit/next-less');
// const nextConfig = require('next/webpack.config')

module.exports = withLess(withSass(withCSS({
    webpack: config => {
        // Fixes npm packages that depend on `fs` module
        config.node = {
            fs: 'empty'
        };
        config.module.rules.push({ test: /\.(png|woff|woff2|eot|ttf|svg|gif)$/, loader: 'url-loader?limit=100000' });

        return config
    }
})));
```

**Comment by hjyue1** [comment] 2019-02-25 09:43
@phucvo0709  Sorry, I have not used nextjs before, so I am not familiar with the configuration, but I think it should be caused by the incorrect configuration of your CSS file. If you can provide an online example, I can try to debug it

**Comment by phucvo0709** [comment] 2019-02-25 12:51
can you convert css to scss today help me?

**Comment by hjyue1** [comment] 2019-02-25 15:25
> can you convert css to scss today help me?

It is recommended that you check the configuration, which is generally a configuration problem，I will close the issue

**Closed as completed by hjyue1** 2019-02-25 15:25 UTC
